// apps/vue-repo/src/components/Card.vue
<script setup lang="ts">
import { format } from 'date-fns';
import type { cardProperty } from 'types';
import { computed } from 'vue';

const props = defineProps([
  'content',
  'comment',
  'cardClickHandler',
]) as cardProperty;

const item = computed(() => props.content || props.comment);
</script>

<template>
  <li
    v-if="item"
    :class="`${item.framework}-shadow ${item.framework}-hover`"
    @click="
      () => {
        if (item) props.cardClickHandler?.(item.id);
      }
    "
  >
    <div class="contents-info">
      <div>
        <img :src="item.profile" />
        <h4>{{ item.username }}</h4>
      </div>
      <img :src="`/public/${item.framework}.svg`" />
    </div>
    <div class="contents-date">
      <h3 v-if="props.content">{{ props.content.title }}</h3>
      <h3 v-if="props.comment">{{ props.comment.comment }}</h3>
      <h3 class="date">{{ format(item.date, 'yyyy/MM/dd') }}</h3>
    </div>
  </li>
</template>

// apps/react-repo/src/components/Card.tsx
import { cardProperty } from 'types';
import { format } from 'date-fns';
import { useMemo } from 'react';

export default function Card(props: cardProperty) {
  const item = useMemo(() => props.content || props.comment, [props]);

  return (
    <>
      {item && (
        <li
          onClick={() => {
            props.cardClickHandler?.(item.id);
          }}
          className={`${item.framework}-shadow ${item.framework}-hover`}
        >
          <div className='contents-info'>
            <div>
              <img src={item.profile} />
              <h4>{item.username}</h4>
            </div>
            <img src={`/public/${item.framework}.svg`} />
          </div>
          <div className='contents-date'>
            {props.content && <h3>{props.content.title}</h3>}
            {props.comment && <h3>{props.comment.comment}</h3>}
            <h3 className='date'>{format(item?.date, 'yyyy/MM/dd')}</h3>
          </div>
        </li>
      )}
    </>
  );
}
