// apps/angular-repo/src/components/Layout.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, Router } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  template: `
    <div class="framework-border angular-border">
      @if(isUser){
      <header>
        <a href="/angular">Angular home</a>
        <button (click)="logoutHandler()">Logout</button>
      </header>
      }
      <router-outlet></router-outlet>
      <div class="framework-title">
        Angular
        <img class="framework-icon" src="/public/angular.svg" />
      </div>
    </div>
  `,
})
export class LayoutComponent {
  constructor(private router: Router) {}

  isUser = true;
  loadCss() {
    const cssList = [
      'main.css',
      'framework.css',
      'list.css',
      'content.css',
      'write.css',
    ];
    cssList.forEach((css) => {
      const link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = '/styles/' + css;
      document.head.appendChild(link);
    });
  }

  logoutHandler = () => {
    sessionStorage.removeItem('user');
    window.location.href = '/';
  };

  ngOnInit() {
    this.loadCss();

    const userJson = sessionStorage.getItem('user');
    if (!userJson) {
      console.log('no user');
      this.isUser = false;
      this.router.navigate(['/angular/not-auth']);
      return;
    }

    const result = JSON.parse(userJson);
    console.log(result.framework);
    if (result.framework !== 'angular') {
      window.location.href = `/${result.framework}`;
      return;
    }
  }
}

// apps/react-repo/src/components/Layout.tsx
import { useEffect, useState } from 'react';
import { Link, Outlet, useNavigate } from 'react-router-dom';

export default function Layout() {
  const navigate = useNavigate();
  const [isUser, setIsUser] = useState(true);

  const logoutHandler = () => {
    sessionStorage.removeItem('user');
    window.location.href = '/';
  };

  useEffect(() => {
    const userJson = sessionStorage.getItem('user');
    if (!userJson) {
      console.log('no user');
      setIsUser(false);
      navigate('/react/not-auth');
      return;
    }

    const result = JSON.parse(userJson);
    console.log(result.framework);
    if (result.framework !== 'react') {
      window.location.href = `/${result.framework}`;
    }
  });

  return (
    <div className='framework-border react-border'>
      <main>
        {isUser && (
          <header>
            <Link to='/react'>React home</Link>
            <button onClick={logoutHandler}>Logout</button>
          </header>
        )}
        <Outlet />
      </main>
      <div className='framework-title'>
        React JS
        <img className='framework-icon' src='/public/react.svg' />
      </div>
    </div>
  );
}
