// apps/vue-repo/src/components/List.vue
<script setup lang="ts">
import '@styles/list.css';

import { onMounted, ref } from 'vue';
import { format } from 'date-fns';

import { RouterLink } from 'vue-router';
import type { contentType, userType } from 'types';
import router from '@/router';

//--------

const userData = ref<userType>();
const contents = ref<contentType[]>([]);

const fetchData = async () => {
  let response = await fetch('/api/contents', { method: 'get' });
  if (response.ok) {
    const result = await response.json();
    contents.value = result;
    console.log(result);
  }
};

onMounted(() => {
  console.log('mounted');
  const userJson = sessionStorage.getItem('user');
  if (!userJson) {
    return;
  }
  const result = JSON.parse(userJson);
  userData.value = result;

  fetchData();
});

const listClickHandler = (id: string) => {
  router.push(`/vue/content/${id}`);
};
</script>

<template>
  <div :class="`user-container ${userData?.framework}-shadow`">
    <div>
      <img :src="userData?.profile" />
      <h1>{{ userData?.username }}</h1>
    </div>
  </div>
  <div class="contents-container default-shadow">
    <div class="contents-header">
      <h2>Contents</h2>
      <RouterLink to="/vue/write">
        <img :src="`/public/pen.svg`" alt="pen|" />
        write
      </RouterLink>
    </div>
    <ol>
      <li
        v-if="Array.isArray(contents) && contents[0]"
        v-for="content in contents"
        :key="content.id"
        :class="`${content.framework}-shadow ${content.framework}-hover`"
        @click="listClickHandler(content.id)"
      >
        <div class="contents-info">
          <div>
            <img :src="content.profile" />
            <h4>{{ content.username }}</h4>
          </div>
          <img :src="`/public/${content.framework}.svg`" />
        </div>
        <div class="contents-date">
          <h3>{{ content.title }}</h3>
          <h3 class="date">{{ format(content?.date, 'yyyy/MM/dd') }}</h3>
        </div>
      </li>

      <div v-else>No contents</div>
    </ol>
  </div>
</template>

// apps/react-repo/src/components/List.tsx
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { contentType, userType } from 'types';
import { format } from 'date-fns';
import '@styles/list.css';

export default function List() {
  const [userData, setUserData] = useState<userType>();
  const [contents, setContents] = useState<contentType[]>();

  const navigate = useNavigate();

  const fetchData = async () => {
    let response = await fetch('/api/contents', { method: 'get' });
    if (response.ok) {
      const result = await response.json();
      setContents(result);
    }
  };

  useEffect(() => {
    const userJson = sessionStorage.getItem('user');
    if (!userJson) {
      return;
    }
    const result = JSON.parse(userJson);
    setUserData(result);

    fetchData();
  }, []);

  const listClickHandler = (id: string) => {
    navigate(`/react/content/${id}`);
  };

  return (
    <>
      <div className={`user-container ${userData?.framework}-shadow`}>
        <div>
          <img src={userData?.profile} />
          <h1>{userData?.username}</h1>
        </div>
      </div>
      <div className='contents-container  default-shadow'>
        <div className='contents-header'>
          <h2>Contents</h2>
          <Link to={`/react/write`}>
            <img src='/public/pen.svg' alt='pen|' />
            write
          </Link>
        </div>
        <ol>
          {contents ? (
            contents.map((content: contentType, i: number) => (
              <li
                onClick={() => {
                  listClickHandler(content.id);
                }}
                key={i}
                className={`${content.framework}-shadow ${content.framework}-hover`}
              >
                <div className='contents-info'>
                  <div>
                    <img src={content.profile} />
                    <h4>{content.username}</h4>
                  </div>
                  <img src={`/public/${content.framework}.svg`} />
                </div>
                <div className='contents-date'>
                  <h3>{content.title}</h3>
                  <h3 className='date'>
                    {format(content?.date, 'yyyy/MM/dd')}
                  </h3>
                </div>
              </li>
            ))
          ) : (
            <div>No contents</div>
          )}
        </ol>
      </div>
    </>
  );
}
