// apps/react-repo/src/pages/Layout.tsx
import { useEffect, useState } from 'react';
import { Link, Outlet, useNavigate } from 'react-router-dom';

export default function Layout() {
	const navigate = useNavigate();
	const [isUser, setIsUser] = useState(true);

	const logoutHandler = () => {
		sessionStorage.removeItem('user');
		window.location.href = '/';
	};

	useEffect(() => {
		const userJson = sessionStorage.getItem('user');
		if (!userJson) {
			console.log('no user');
			setIsUser(false);
			navigate('/react/not-auth');
			return;
		}

		const result = JSON.parse(userJson);
		console.log(result.framework);
		if (result.framework !== 'react') {
			window.location.href = `/${result.framework}`;
		}
	});

	return (
		<div className="framework-border react-border">
			<div className="main-container">
				{isUser && (
					<header>
						<Link to="/react">React home</Link>
						<button onClick={logoutHandler}>Logout</button>
					</header>
				)}
				<main>
					<Outlet />
				</main>
			</div>
			<div className="framework-title">
				React JS
				<img className="framework-icon" src="/public/react.svg" />
			</div>
		</div>
	);
}

// apps/vue-repo/src/pages/Layout.vue
<script setup lang="ts">
import router from '@/router';
import { onMounted, ref } from 'vue';
import { RouterView } from 'vue-router';

const isUser = ref(true);

const logoutHandler = () => {
	sessionStorage.removeItem('user');
	window.location.href = '/';
};

onMounted(() => {
	const userJson = sessionStorage.getItem('user');
	if (!userJson) {
		console.log('no user');
		isUser.value = false;
		router.push('/vue/not-auth');
		return;
	}

	const result = JSON.parse(userJson);
	console.log(result.framework);
	if (result.framework !== 'vue') {
		window.location.href = `/${result.framework}`;
	}
});
</script>

<template>
	<div class="framework-border vue-border">
		<div class="main-container">
			<header v-if="isUser">
				<RouterLink to="/vue">Vue home</RouterLink>
				<button @click="logoutHandler">Logout</button>
			</header>

			<main>
				<RouterView />
			</main>
		</div>
		<div class="framework-title">
			Vue
			<img class="framework-icon" :src="`/public/vue.svg`" />
		</div>
	</div>
</template>
